version: '3.8'

services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq_demo
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: >
      bash -c "
      rabbitmq-plugins enable rabbitmq_management &&
      rabbitmq-server
      "
volumes:
  rabbitmq_data: